replicaCount: 2

image:
  repository: node
  tag: "18-alpine"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Cloud-specific configurations
cloud:
  provider: ""
  region: ""
  
# Environment-specific settings
environment: "default"