replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - app1
        topologyKey: kubernetes.io/hostname

# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: app.lebo.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Cloud-specific configurations
cloud:
  provider: ""
  region: ""
  
# Environment-specific settings
environment: "default"