replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: Always

# Blue-Green Deployment Configuration
blueGreen:
  # Which version is currently active: blue or green
  active: blue
  blue:
    replicaCount: 2
    tag: "1.25"
  green:
    replicaCount: 2
    tag: "1.25"

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - app1
        topologyKey: kubernetes.io/hostname

# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: app.lebo.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Cloud-specific configurations
cloud:
  provider: ""
  region: ""
  
# Environment-specific settings
environment: "default"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

podSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - NET_RAW