{{- if .Values.blueGreen }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app1.fullname" . }}-blue
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
    version: blue
    app.kubernetes.io/color: blue
spec:
  replicas: {{ .Values.blueGreen.blue.replicaCount | default .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app1.selectorLabels" . | nindent 6 }}
      version: blue
  template:
    metadata:
      labels:
        {{- include "app1.selectorLabels" . | nindent 8 }}
        version: blue
        app.kubernetes.io/color: blue
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.blueGreen.blue.tag | default .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: CLOUD_PROVIDER
          value: {{ .Values.cloud.provider | quote }}
        - name: CLOUD_REGION
          value: {{ .Values.cloud.region | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEPLOYMENT_COLOR
          value: "blue"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}