{{- if .Values.blueGreen }}
{{- $inactiveColor := "green" }}
{{- if eq .Values.blueGreen.active "green" }}
{{- $inactiveColor = "blue" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app1.fullname" . }}-preview
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
    app.kubernetes.io/color: {{ $inactiveColor }}
    app.kubernetes.io/role: preview
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "app1.selectorLabels" . | nindent 4 }}
    version: {{ $inactiveColor }}
{{- end }}