{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: 3000
    protocol: TCP
    name: http
  {{- with .Values.grafana.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: grafana
{{- end }}