{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    cloud: {{ .Values.cloud.provider }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.adminPassword | quote }}
        - name: CLOUD_PROVIDER
          value: {{ .Values.cloud.provider | quote }}
        - name: CLOUD_REGION
          value: {{ .Values.cloud.region | quote }}
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
{{- end }}