replicaCount: 3

cloud:
  provider: "aws"
  region: "eu-west-1"

environment: "aws-eks"

# AWS-specific node selector and affinity
nodeSelector:
  kubernetes.io/os: linux
  node.kubernetes.io/instance-type: t3.medium

# AWS-specific pod affinity
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eu-west-1a
          - eu-west-1b
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - app1
      topologyKey: kubernetes.io/hostname

# AWS topology spread constraints
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: app1

# AWS-specific resource requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# AWS Load Balancer service type
service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"