cloud:
  provider: "azure"
  region: "East US"

environment: "azure-aks"

controller:
  replicaCount: 2
  
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: "platform-poc-rg"
  
  resources:
    limits:
      cpu: 150m
      memory: 200Mi
    requests:
      cpu: 75m
      memory: 100Mi
  
  nodeSelector:
    kubernetes.io/os: linux
    agentpool: default
  
  config:
    use-proxy-protocol: "false"
    use-forwarded-headers: "true"