replicaCount: 2

# Blue-Green Deployment Configuration
blueGreen:
  active: blue
  blue:
    replicaCount: 2
    tag: "1.25"
  green:
    replicaCount: 2
    tag: "1.25"

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "my-resource-group"

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/os: linux

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - eastus-1
          - eastus-2
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - app1
        topologyKey: kubernetes.io/hostname

topologySpreadConstraints:
  - maxSkew: 2
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: app1

cloud:
  provider: "azure"
  region: "eastus"

environment: "azure-aks"