prometheus:
  enabled: true
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: "v2.45.0"
  service:
    type: ClusterIP
    port: 9090
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

grafana:
  enabled: true
  replicaCount: 1
  image:
    repository: grafana/grafana
    tag: "10.0.0"
  service:
    type: LoadBalancer
    port: 3000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  adminPassword: "admin123"

# Cloud-specific configurations
cloud:
  provider: ""
  region: ""
  
# Environment-specific settings
environment: "default"