cloud:
  provider: "aws"
  region: "eu-west-1"

environment: "aws-eks"

controller:
  replicaCount: 2
  
  admissionWebhooks:
    enabled: true
  
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  nodeSelector:
    kubernetes.io/os: linux
  
  config:
    use-proxy-protocol: "true"
    use-forwarded-headers: "true"