controller:
  replicaCount: 2
  image:
    repository: registry.k8s.io/ingress-nginx/controller
    tag: "v1.9.4"
    pullPolicy: IfNotPresent
  
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
    annotations: {}
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  nodeSelector: {}
  tolerations: []
  affinity: {}
  
  # Ingress class configuration
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  
  # Configuration options
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "false"

# Cloud-specific configurations
cloud:
  provider: ""
  region: ""

# Environment-specific settings
environment: "default"