apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lebo2025/kubernetes-poc.git
    targetRevision: main
    path: gitops/applications/overlays/aws-eks
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
